fix error in static analysing code PSALM
ERROR: UndefinedDocblockClass:
Docblock-defined class or interface Hemp\Presenter\Hemp\Presenter does not exist